# Generated by Django 5.0.4 on 2024-11-04 15:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("pybirdai", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="abstrct_instrmnt_rl",
            name="GRSS_CRRYNG_AMNT",
        ),
    ]
