# Generated by Django 5.1.4 on 2025-01-13 20:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("pybirdai", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="fnncl_asst_instrmnt_drvd_dt",
            name="GRSS_CRRYNG_AMNT",
        ),
    ]
